In [2]:
import pandas as pd

In [3]:
df = pd.read_json('yelp_academic_dataset_tip.json', lines=True)

df.head()

,user_id,business_id,text,date,compliment_count
0,WCjg0jdHXMlwbqS9tZUx8Q,ENwBByjpoa5Gg7tKgxqwLg,Carne asada chips...,2011-07-22 19:07:35,0
1,42-Z02y9bABShAGZhuSzrQ,jKO4Og6ucdX2-YCTKQVYjg,Best happy hour from 3pm to 6pm! $1 off martin...,2014-09-10 07:33:29,0
2,5u7E3LYp_3eB8dLuUBazXQ,9Bto7mky640ocgezVKSfVg,"Nice people, skilled staff, clean location - b...",2013-12-13 23:23:41,0
3,wDWoMG5N9oI4DJ-p7z8EBg,XWFjKtRGZ9khRGtGg2ZvaA,"1/2-price bowling & the ""Very"" Old Fashion are...",2017-07-11 23:07:16,0
4,JmuFlorjjRshHTKzTwNtgg,mkrx0VhSMU3p3uhyJGCoWA,"Solid gold's. Great sauna. Great staff, too. E...",2016-11-30 08:46:36,0

In [4]:
clean_df = df.dropna(how='all')

In [5]:
# 2019-2021

dated_df = pd.to_datetime(df["date"])
sorted_df = df.sort_values(["date"], ascending= False)
sorted_df.head()

,user_id,business_id,text,date,compliment_count
669130,q4YuIIWaekF_lrYFCG440A,I2OblwJG8_XzFxxoHU0vVQ,Surgeries are only completed on Thursdays only...,2021-01-28 14:20:15,0
820468,63UoTNVbHn35th-pgp6UKw,vQ0ihvqI0Xpz8TxBIKK_qg,Best donuts in town. Staff is super friendly.,2021-01-28 14:11:48,0
508765,Ouz4R8N4pDyYBqML6zb-ZA,7rEr-_j7NT2YZMFIi3KdpA,Temporarily closed today due to covid.,2021-01-28 14:01:20,0
656329,Q_fbXeB2HyRg6CmctrICKw,wegBPIo-9hnuEtAaY2xYvw,Try the chocolate cookie-ice cream sandwich. ...,2021-01-28 13:26:55,0
1148517,eseZ_gMjqBQMtyHyPpDMLA,t5EgwRXG6MZSihdqugOSKg,Great place,2021-01-28 11:57:22,0

In [10]:
relevant_df = sorted_df[sorted_df['date'] > "2019-1-1"]
relevant_df

,user_id,business_id,text,date,compliment_count
669130,q4YuIIWaekF_lrYFCG440A,I2OblwJG8_XzFxxoHU0vVQ,Surgeries are only completed on Thursdays only...,2021-01-28 14:20:15,0
820468,63UoTNVbHn35th-pgp6UKw,vQ0ihvqI0Xpz8TxBIKK_qg,Best donuts in town. Staff is super friendly.,2021-01-28 14:11:48,0
508765,Ouz4R8N4pDyYBqML6zb-ZA,7rEr-_j7NT2YZMFIi3KdpA,Temporarily closed today due to covid.,2021-01-28 14:01:20,0
656329,Q_fbXeB2HyRg6CmctrICKw,wegBPIo-9hnuEtAaY2xYvw,Try the chocolate cookie-ice cream sandwich. ...,2021-01-28 13:26:55,0
1148517,eseZ_gMjqBQMtyHyPpDMLA,t5EgwRXG6MZSihdqugOSKg,Great place,2021-01-28 11:57:22,0
...,...,...,...,...,...
431164,K-2-4KsCg_fEvc7xrS5yyA,viqkunBBI6QOIZehME-7gg,Great,2019-01-01 00:35:54,0
399487,TSHoVpWNd-mwjAw_kkSOfQ,zmRHDJq8qgWoVYobHL2ggg,Go buy an Android. This mall kiosk is a joke. ...,2019-01-01 00:31:17,0
435268,aBQZ_rREkyaQRpH9XjnjSA,tUhIIaYSjBuSbJzcf6CGIg,"Good stuff, always fresh and hot!",2019-01-01 00:27:50,0
952571,bMGIATKbYqPu8lkyLirvBw,bORoF6fOYu39jHgzNyiKiA,The bathroom doors aren't marked! The Japanese...,2019-01-01 00:15:42,0
1005768,yd9N1h-A8SrMnh6HtqHXiA,KAD2Vk1_qXX_utyv8Ndsow,Not a lot of good to say. Limited menu. Limit...,2019-01-01 00:05:28,0

In [12]:
business_df = pd.read_json('yelp_academic_dataset_business.json', lines=True)

business_df.head()

ValueError: Expected object or value